BookStore.WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 5;

        public BookController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.Books
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(Book => Book.BookId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Books.Count() :
                repository.Books.Where(Book => Book.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int BookId)
        {
            Book Book = repository.Books
                .FirstOrDefault(g => g.BookId == BookId);

            if (Book != null)
            {
                return File(Book.ImageData, Book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

BookStore.WebUI/Controllers/CartController.cs
using System.Linq;
using System.Web.Mvc;
using BookStore.Domain.Entities;
using BookStore.Domain.Abstract;
using BookStore.WebUI.Models;

namespace BookStore.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IBookRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }

        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Извините, ваша корзина пуста!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToRouteResult AddToCart(Cart cart, int BookId, string returnUrl)
        {
            Book Book = repository.Books
                .FirstOrDefault(g => g.BookId == BookId);

            if (Book != null)
            {
                cart.AddItem(Book, 1);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int BookId, string returnUrl)
        {
            Book Book = repository.Books
                .FirstOrDefault(g => g.BookId == BookId);

            if (Book != null)
            {
                cart.RemoveLine(Book);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }
    }
}

BookStore.WebUI/Controllers/NavController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using BookStore.Domain.Abstract;

namespace BookStore.WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string category = null, bool horizontalNav = false)
        {
            ViewBag.SelectedCategory = category;

            IEnumerable<string> categories = repository.Books
                .Select(Book => Book.Category)
                .Distinct()
                .OrderBy(x => x);

            string viewName = horizontalNav ? "MenuHorizontal" : "Menu";
            return PartialView(viewName, categories);
        }
    }
}

BookStore.WebUI/Views/Shared/BookSummary.cshtml
@model BookStore.Domain.Entities.Book

<div class="well" style="clear: both; float: left;">
    <div class="pull-left"
         style="margin-right: 10px; 
                flex-direction: column; 
                display: flex; 
                margin-bottom: 0px;">
        @using (Html.BeginForm("AddToCart", "Cart"))
        {
            <div class="pull-right">
                @Html.HiddenFor(x => x.BookId)
                @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            </div>
            <input type="submit" 
                   class="btn btn-success" 
                   value="Добавить" />
        }

        @if (Model.ImageData != null)
        {
            <img class="img-thumbnail" 
                 style="margin-top: 15px;" 
                        width="130" 
                        height="130" 
                 src="@Url.Action("GetImage", "Book", 
                        new { Model.BookId })" />
        }
    </div>
    <h3>
        <strong>@Model.Name</strong>
    </h3>

    <span class="lead">@Model.Description</span>
</div>

BookStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.9.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>
</head>
<body>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
</body>
</html>

BookStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <!-- Bootstrap стили -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyles.css" rel="stylesheet" />
    <!-- Инструкция для IE -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Отображать страницу в масштабе 100% -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Нормализация стилей -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.0/normalize.css">
    <!-- Собственные стили -->
    <link rel="stylesheet" href="~/Content/myStyles/css/main.css">
    <link rel="shortcut icon" type="image/x-icon" href="~/Content/myStyles/img/favicon/favicon.png">
    <!-- Подключение веб-шрифтов -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather|PT+Sans+Caption:400,700&amp;subset=cyrillic-ext">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="background">
        <!--=========== HEADER ===========-->
        <div class="header">
            <div class="header-box">
                <div class="box-col" style="margin-right: 60px;"> <img class="logo-img" src="~/Content/myStyles/img/main-page/logo.png" alt="BookStore" height="70"> </div>
                <div class="box-col"  style="margin-right: 20px;"> <div class="link-txt"> <a href="#"> главная </a> </div> </div>
                <div class="box-col"> <div class="link-txt"> <a href="#"> библеотека </a> </div> </div>
                <div class="box-col" style="width: 200px; margin-right: 80px; margin-left: 70px;">
                    @using (Html.BeginForm())
                    {
                        <div class="row" id="find">
                            <div class="col-sm-3 input-group" style="display: flex;">
                                <span> <button type="submit" class="btn btn-default"> Найти </button> </span>
                                <input type="text" class="form-control" style="width: 200px;" name="filter" value="@ViewBag.filter" placeholder="Поиск книги..." />
                            </div>
                        </div>
                    }
                </div>
                <div class="box-col">
                    <div class="autorize-box">
                        <div class="log-txt"> <a href="~/account/login"> войти </a> </div>
                    </div>
                </div>
            </div>
        </div>
        <!--=========== PAGE ===========-->
        <div class="page">
            <div class="cart">
                <div class="books-body">
                    <div id="categories">
                        @Html.Action("Menu", "Nav", new { horizontalNav = true })
                    </div>
                </div>
                @Html.Action("Summary", "Cart")
            </div>
            <div class="page-box">
                <div class="right-box">
                    @RenderBody()
                </div>
            </div>
        </div>
        <!--=========== FOOTER ===========-->
        <div class="footer">
            <div class="footer-box">
                <div class="fbox-col"> <p class="footer-txt"> адрес в Казани: ул.Гагарина 75a </p> </div>
                <div class="fbox-col">
                    <p class="footer-txt"> наши контакты <br> +7(962)777-77-77 <br> BookStore@gmail.com </p>
                </div>
                <div class="fbox-col">
                    <p class="footer-txt"> мы в социальных сетях </p>
                    <p class="footer-icons">
                        <a href="#" target="_blank"> <i class="fa fa-vk" aria-hidden="true"></i> </a>
                        <a href="#" target="_blank"> <i class="fa fa-twitter" aria-hidden="true"></i> </a>
                        <a href="#" target="_blank"> <i class="fa fa-facebook" aria-hidden="true"></i> </a>
                        <a href="#" target="_blank"> <i class="fa fa-instagram" aria-hidden="true"></i> </a>
                        <a href="#" target="_blank"> <i class="fa fa-youtube" aria-hidden="true"></i> </a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>