BookStore.WebUI/Controllers/AdminController.cs
using System.Web.Mvc;
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using System.Linq;
using System.Web;

namespace BookStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IBookRepository repository;

        public AdminController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Books);
        }

        public ViewResult Edit(int BookId)
        {
            Book Book = repository.Books
                .FirstOrDefault(g => g.BookId == BookId);
            return View(Book);
        }

        // Перегруженная версия Edit() для сохранения изменений
        [HttpPost]
        public ActionResult Edit(Book Book, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    Book.ImageMimeType = image.ContentType;
                    Book.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(Book.ImageData, 0, image.ContentLength);
                }
                repository.SaveBook(Book);
                TempData["message"] = string.Format("Изменения в книге \"{0}\" были сохранены", Book.Name);
                return RedirectToAction("Index");
            }
            else
            {
                // Что-то не так со значениями данных
                return View(Book);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Book());
        }

        [HttpPost]
        public ActionResult Delete(int BookId)
        {
            Book deletedBook = repository.DeleteBook(BookId);
            if (deletedBook != null)
            {
                TempData["message"] = string.Format("Книга \"{0}\" была удалена",
                    deletedBook.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

BookStore.WebUI/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BookStore.Domain.Abstract;
using BookStore.Domain.Entities;
using BookStore.WebUI.Models;

namespace BookStore.WebUI.Controllers
{
    public class BookController : Controller
    {
        private IBookRepository repository;
        public int pageSize = 5;

        public BookController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.Books
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(Book => Book.BookId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                repository.Books.Count() :
                repository.Books.Where(Book => Book.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int BookId)
        {
            Book Book = repository.Books
                .FirstOrDefault(g => g.BookId == BookId);

            if (Book != null)
            {
                return File(Book.ImageData, Book.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

BookStore.WebUI/Views/Admin/Edit.cshtml
@model BookStore.Domain.Entities.Book

@{
    ViewBag.Title = "Админ панель: редактирование товара";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link rel="stylesheet" href="~/Content/myStyles/css/main.css">
<link rel="shortcut icon" type="image/x-icon" href="~/Content/myStyles/img/favicon/favicon.png">


<div class="background-edit">
    <div class="edit-box">
        <div class="head-edit">
            <h3>Редактирование книги «@Model.Name»</h3>
        </div>

        @using (Html.BeginForm("Edit", "Admin",
            FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="panel-body">
                @Html.HiddenFor(m => m.BookId)
                @foreach (var property in ViewData.ModelMetadata.Properties)
                {
                    switch (property.PropertyName)
                    {
                        case "BookId":
                        case "ImageData":
                        case "ImageMimeType":
                            // Ничего не делать
                            break;
                        default:
                            <div class="form-group">
                                <label>@(property.DisplayName ?? property.PropertyName)</label>
                                @if (property.PropertyName == "Description")
                                {
                                    @Html.TextArea(property.PropertyName, null,
                                        new { @class = "form-control", rows = 5 })
                                }
                                else
                                {
                                    @Html.TextBox(property.PropertyName, null,
                                        new { @class = "form-control" })
                                }
                                @Html.ValidationMessage(property.PropertyName)
                            </div>
                            break;
                    }
                }
                <div class="form-group">
                    <div style="position:relative;">
                        <label>Картинка</label>
                        <a class='btn' href='javascript:;'>
                            Выберите файл...
                            <input type="file" name="Image" size="40"
                                    style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                                    onchange='$("#upload-file-info").html($(this).val());'>
                        </a>
                        <span class='label label-info' id="upload-file-info"></span>
                    </div>
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">Нет картинки</div>
                    }
                    else
                    {
                        <img class="img-thumbnail" width="150" height="150"
                                src="@Url.Action("GetImage", "Book",
                        new { Model.BookId })" />
                    }
                </div>
            </div>
            <div class="panel-footer">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
                @Html.ActionLink("Отменить изменения и вернуться к списку", "Index", null, new
                {
                    @class = "btn btn-default"
                })
            </div>
        }
    </div>
</div>

BookStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<BookStore.Domain.Entities.Book>

@{
    ViewBag.Title = "Админ панель: список товаров";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список книг</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered" >
            <tr>
                <th class="text-right">ID</th>
                <th style="width: 150vh;">Название</th>
                <th class="text-right" style="width: 200px;">Статус</th>
                <th class="text-center" style="display: flex;">Действия</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.BookId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.BookId })</td>
                    <td class="text-right">в наличии</td>
                    <td class="text-center" 
                        style="display: flex; 
                               justify-content: center;">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("BookId", item.BookId)
                            <input type="submit" 
                                   class="btn btn-default btn-xs" 
                                   style="margin-right: 10px;" 
                                   value="Удалить" />
                        }
                        @using (Html.BeginForm("Edit", "Admin"))
                        {
                            @Html.Hidden("BookId", item.BookId)
                            <input type="submit" 
                                   class="btn btn-default btn-xs" 
                                   value="Изменить" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавить книгу", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>